steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/gitops-update-manifest:latest',
    '-t', 'gcr.io/$PROJECT_ID/gitops-update-manifest:${_VERSION}',
    '.'
  ]

images: [
  'gcr.io/$PROJECT_ID/gitops-update-manifest:latest',
  'gcr.io/$PROJECT_ID/gitops-update-manifest:${_VERSION}',
]

substitutions:
  _VERSION: 1.0.0

