steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    docker build -t gcr.io/$PROJECT_ID/safetyamp-web:$SHORT_SHA build/nginx && \
    docker build -t gcr.io/$PROJECT_ID/safetyamp-api:$SHORT_SHA .

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    docker push gcr.io/$PROJECT_ID/safetyamp-web:$SHORT_SHA && \
    docker push gcr.io/$PROJECT_ID/safetyamp-api:$SHORT_SHA

- id: Generate Manifest
  name: 'gcr.io/$PROJECT_ID/gitops-update-manifest'
  args:
  - --branch=staging
  - --origin=git@bitbucker.org:hrdl/env.git
  - 'api.image=gcr.io/$PROJECT_ID/safetyamp-api:$SHORT_SHA'
  - 'web.image=gcr.io/$PROJECT_ID/safetyamp-web:$SHORT_SHA'
  env:
  - 'SSH_KEY=$_BITBUCKET_SSH_KEY'
